project:
  key: GHSPECS
  plan:
    key: SLAYAML
    name: Dragon Slayer YAML
stages:
  - jobs:
      - scripts:
          - echo 'Going to slay the red dragons, watch me'
          - sleep 4
          - echo 'Nailed it'
